### ISSUE TITLE
Add the possibility to add margin around the form

### ISSUE THREAD

**Issue by MscrmTools** [temmyraharjo/pcf-form-json#1]
As you can see in this [little video](https://www.screencast.com/t/arQ22aEhhLF), I'm using your component to create a simple dialog.

It would be nice to be able to add margin around the form so it fits better in this situation

**Comment by temmyraharjo** [comment]
I add already the margin. Please check it out.

https://github.com/temmyraharjo/pcf-form-json/commit/41b8ccf06acd17c7657c3d30df5e02653f12dcce
