### ISSUE TITLE
Support for OptionSet?

### ISSUE THREAD

**Issue by MscrmTools** [temmyraharjo/pcf-form-json#2]
Do you consider adding support for OptionSet?

**Comment by temmyraharjo** [comment]
Thanks for the input. I added 2 types: optionset + date. Please look at the input type + metadata option for generate the optionset.

https://github.com/temmyraharjo/pcf-form-json/commit/41b8ccf06acd17c7657c3d30df5e02653f12dcce

**Comment by MscrmTools** [comment]
Great! That will really help!
