### ISSUE TITLE
Facing issue while configuring the control

### ISSUE THREAD

**Issue by asta96-zz** [temmyraharjo/pcf-form-json#3]
i am facing issue while trying to set up this control on my trial. I am using Description field to capture both Value and for the control. Please let me know if i am doing something wrong. 

![image](https://user-images.githubusercontent.com/58759544/117912393-1133a780-b2fd-11eb-803e-b95480b4c8a4.png)

Error 
![image](https://user-images.githubusercontent.com/58759544/117912557-56f07000-b2fd-11eb-9a06-7b53ae03de19.png)

my field configuration at account form
![image](https://user-images.githubusercontent.com/58759544/117912651-7daea680-b2fd-11eb-9ec5-717cc39aaf13.png)

**Comment by temmyraharjo** [comment]
Hi @asta96 . This PCF Form need  2 parameters to be set (1 bound, 1 input only). _**String Property**_ will be bound attribute for defining the result after you press Save button in the form. While _**Control Form Json**_ will be the metadata for the form which you can't put the value as the same as the _**String Property**_ . I updated the Readme.md. Please take a look how I setup the PCF there. Thank you.

**Comment by asta96-zz** [comment]
Thank you @temmyraharjo  you are great. Pardon my misunderstanding. Now working fine

**Comment by temmyraharjo** [comment]
@asta96 It's totally fine. Meaning the project's documentation still not clear enough and with this kind of feedback I only know how to make it better.
