### ISSUE TITLE
lookup.ts error

### ISSUE THREAD

**Issue by JFulfordMS** [temmyraharjo/pcf-form-json#4]
https://github.com/temmyraharjo/pcf-form-json/blob/0d50449ca2b1541af2791b9878c74834fde078d4/JsonFormComponent/controls/lookup.ts#L18

./JsonFormComponent/controls/lookup.ts 18:6-56
[tsl] ERROR in E:\PowerAppComps\JsonFormControl\JsonFormComponent\controls\lookup.ts(18,7)
      TS2345: Argument of type '(value: ComponentFramework.EntityReference[]) => void' is not assignable to parameter of type '(value: LookupValue[]) => void | PromiseLike<void>'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'LookupValue[]' is not assignable to type 'EntityReference[]'.
      Type 'LookupValue' is not assignable to type 'EntityReference'.
        Types of property 'id' are incompatible.
          Type 'string' is not assignable to type '{ guid: string; }'.

**Comment by temmyraharjo** [comment]
Hi @JFulfordMS, try install the latest version and retry again.
